### ISSUE TITLE
Broker selection fields on install

### ISSUE THREAD

**Issue by matzew** [knative/eventing-operator#175]
**Problem**

0.14 will come with two brokers:
* channel based 
* multitenant channel broker

There are now different artifacts, that we need to take into account.

We have two convenient release yamls:
* [`eventing.yaml`](https://github.com/knative/eventing/blob/master/hack/release.sh#L35): this have the the `channel` version
* [`eventing-mt.yaml`](https://github.com/knative/eventing/blob/master/hack/release.sh#L36): this will have the multitenant version

However,  that means you pick one or the other.

Generally the artifacts we ship are:
*  `eventing-crds.yaml`
* `eventing-core.yaml` 
* `channel-broker.yaml` 
* `mt-channel-broker.yaml`

How about we have the operator to apply the first two yamls, and based on installation choice (or later updated CR), we pick which broker we apply?

The default would be `channel`,

```yaml
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  broker: channel
```

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?

* System integrator

**Exit Criteria**

installation of broker done, based on `broker` field

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by houshengbo** [comment]
@matzew So far, the manifest is loaded before creating the CR.
To make CR configuration able to determine how to load the manifest:

One way is to load different manifest in the controller, and use a map with key-value, maintaining in the reconciler. By different CR broker configurations, reconciler can select the correct manifest, with the key of the map.

The other way is to dynamically load the manifest in reconciler. Each time reconciling loop is kicked-off, load the manifest at this beginning, based on CR.

@jcrossley3 What do you think?

**Comment by houshengbo** [comment]
What about we add the validation webhook in eventing-operator?
The old value of the CR is saved in the context.

Then, implement the function Validate for the eventing CR, similar to https://github.com/knative/serving/blob/master/pkg/apis/serving/v1beta1/route_validation.go#L35 to retrieve the existing value, when it is an update.

If the new value for broker is the same as the existing one, we move on. If not, raise an error, stating that `Users need to stay with the old broker. If u want to change, you need to remove and recreate the CR.`

**Comment by houshengbo** [comment]
As I discussed with @n3wscott. All the channels can be installed and run at the same time without influencing each other, we do not necessarily need to delete other channels, before installing the channel we select.
@jcrossley3 @matzew @aliok

**Comment by matzew** [comment]
Not exactly sure what this `broker` field has to do with the channels.

But there is a some difference in the way the other channels come and bundle their yamls.:
None of the other channels, come w/ a `ConfigMap` (`config-br-defaults`) override to set themselves as `default`.

The brokers both, come with the same configmap, with different values:
* https://storage.googleapis.com/knative-nightly/eventing/latest/mt-channel-broker.yaml
* https://storage.googleapis.com/knative-nightly/eventing/latest/channel-broker.yaml

both have them... 

so if you apply the first, than the second, they do have effect. 

Channels do not do that....

No config maps in here, which does SET the channel as default
* https://github.com/knative/eventing/tree/master/config/channels/in-memory-channel
* https://github.com/knative/eventing-contrib/tree/master/natss/config
* https://github.com/knative/eventing-contrib/tree/master/kafka/channel/config

**Comment by aliok** [comment]
What I understand is:
1. Having both brokers at the same time is possible
2. `mt-channel-broker.yaml` and `channel-broker.yaml` has some resources twice. 
** Some of them are conflicting, like `config-br-defaults` configMap, which sets the mtbroker or the channelBroker as the default broker
** Some of them are simply identical

With @matzew 's PR, https://github.com/knative/eventing/pull/2936, non-conflicting stuff is going to be in the YAML and the conflicting stuff will be separate, so that they can be applied invididually.

e.g., apply the release yaml, then
* apply [this](https://raw.githubusercontent.com/knative/eventing/2c1c5c2e2e7cbb36a716e6fca8802f71704775ff/config/400-config-br-defaults.yaml) and you have the `ChannelBasedBroker` as the default
* apply [this](https://raw.githubusercontent.com/knative/eventing/2c1c5c2e2e7cbb36a716e6fca8802f71704775ff/test/config/mt-channel-broker.yaml) and you have the `MTChannelBasedBroker` as the default broker.

I like the idea of having `broker` field in the CR. The value of that should the `brokerClass` names that are possible to pass into `default-br-config`. So, `ChannelBasedBroker` and `MTChannelBasedBroker` for now, and maybe others in the future.

**Comment by aliok** [comment]
/assign @aliok 

I have the bandwidth to work on this one

**Comment by houshengbo** [comment]
Thanks @aliok

**Comment by aliok** [comment]
I suggest the field to be called 
- `defaultBrokerClass`:  consistent with the `default-br-config` (https://raw.githubusercontent.com/knative/eventing/2c1c5c2e2e7cbb36a716e6fca8802f71704775ff/config/400-config-br-defaults.yaml)
OR
- `defaultBroker`

Ex:
```
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing
spec:
  defaultBrokerClass: ChannelBasedBroker
```

**Comment by houshengbo** [comment]
I see `brokerClass`, not `defaultBrokerClass`.
