### ISSUE TITLE
I don't think the short name `ke` should be set

### ISSUE THREAD

**Issue by n3wscott** [knative/eventing-operator#38]
There is a finite amount of two letter short names that k8s can have, if we reserve 'ke' for the knative eventing operator I worry about the future conflicts for resources that someone might interact with often. I do not expect someone to be touching the eventing operator object very much and a fully qualified name to use it seems to not be that big of deal.

**Comment by matzew** [comment]
I'd think that `keo` even makes more sense, than `ke`. In redhat we do internally speak about these as `k-s-o` or `k-e-o` ...

However, if we change here, we should... perhaps do so for serving as well:
https://github.com/knative/serving-operator/blob/master/config/300-serving-v1alpha1-knativeserving-crd.yaml#L23

/cc @jcrossley3

**Comment by aliok** [comment]
IMO, with `kubectl` autocomplete, I never care about the short names like that.
Is there any other case other than `kubectl` that make use of short names?

**Comment by jcrossley3** [comment]
I like the short name. And I miss when it doesn't work because I have both `knativeservings.operator.knative.dev` and `knativeservings.serving.knative.dev` installed, for which I also blame y'all. :stuck_out_tongue_winking_eye: 

I wouldn't want to change it to `kso` or `keo` because those imply the operator to me, rather than the CR it's watching. I could live with `kserve` or `kevent` maybe.

If we remove it, I'll need to spend some time and figure out how to make `kubectl` autocomplete work in an emacs shell.

Is the k8s community really approaching the limit of 2-letter name exhaustion?

**Comment by aliok** [comment]
We can close this issue as the short name is already deleted during this PR: https://github.com/knative/eventing-operator/pull/48

cc @k4leung4
